// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sU5nH41YDcp1Z8qIDFIM5WnqAlwT4NY',
    appId: '1:348191564859:android:e968d86eb14ed94102281e',
    messagingSenderId: '348191564859',
    projectId: 'navoramapa',
    storageBucket: 'navoramapa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRxETyhfj-pPTFzCkm15fgUXFLF6qA5w',
    appId: '1:348191564859:ios:93702b7970299e9a02281e',
    messagingSenderId: '348191564859',
    projectId: 'navoramapa',
    storageBucket: 'navoramapa.firebasestorage.app',
    iosBundleId: 'com.navora.app',
  );
}

